(() => {
  const data = [
    { topic:'Niat', reference:'Sahih al-Bukhari, no. 1 · Sahih Muslim, no. 1907', arabic:'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى', malay:'Sesungguhnya setiap amalan bergantung pada niat, dan setiap orang hanya mendapat apa yang diniatkannya.' },
    { topic:'Ilmu Al-Quran', reference:'Sahih al-Bukhari, no. 5027', arabic:'خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ', malay:'Sebaik-baik kamu ialah orang yang mempelajari Al-Quran dan mengajarkannya.' },
    { topic:'Akhlak', reference:'Jami\' al-Tirmidhi, no. 1956', arabic:'تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ', malay:'Senyumanmu kepada saudaramu ialah satu sedekah.' },
    { topic:'Kebaikan', reference:'Sahih Muslim, no. 1009', arabic:'كُلُّ مَعْرُوفٍ صَدَقَةٌ', malay:'Setiap kebaikan ialah sedekah.' },
    { topic:'Persaudaraan', reference:'Sahih Muslim, no. 2699', arabic:'وَمَنْ فَرَّجَ عَنْ مُسْلِمٍ كُرْبَةً فَرَّجَ اللَّهُ عَنْهُ بِهَا كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ', malay:'Sesiapa yang melapangkan satu kesusahan seorang Muslim, Allah akan melapangkan baginya satu kesusahan pada hari kiamat.' },
    { topic:'Sedekah', reference:'Sahih al-Bukhari, no. 6021 · Sahih Muslim, no. 47', arabic:'فَمَنْ لَمْ يَجِدْ فَبِكَلِمَةٍ طَيِّبَةٍ', malay:'Sesiapa yang tidak mampu, maka dengan kata-kata yang baik.' }
  ];
  const list = document.querySelector('#hadis-list'); const search = document.querySelector('#hadis-search'); const count = document.querySelector('#hadis-count'); const filter = document.querySelector('#hadis-favourite-filter');
  const key = 'sedekahqr-hadis-favourites'; let saved = new Set(JSON.parse(localStorage.getItem(key) || '[]'));
  const render = () => { const query = search.value.trim().toLowerCase(); const favouritesOnly = filter.getAttribute('aria-pressed') === 'true'; const shown = data.filter((hadis, index) => (!favouritesOnly || saved.has(index)) && `${hadis.topic} ${hadis.reference} ${hadis.malay}`.toLowerCase().includes(query)); list.replaceChildren(); count.textContent = `${shown.length} hadis`; if (!shown.length) { list.innerHTML = '<p class="hadis-empty">Tiada hadis sepadan dengan carian atau simpanan anda.</p>'; return; } shown.forEach((hadis) => { const index = data.indexOf(hadis); const card = document.createElement('article'); card.className = 'hadis-card'; const head = document.createElement('header'); head.className = 'hadis-card-head'; head.innerHTML = `<div><p class="hadis-topic">${hadis.topic.toUpperCase()}</p><p class="hadis-reference">${hadis.reference}</p></div>`; const button = document.createElement('button'); button.className = 'hadis-save'; button.type = 'button'; button.title = 'Simpan hadis'; button.setAttribute('aria-label','Simpan hadis'); button.setAttribute('aria-pressed', String(saved.has(index))); button.textContent = saved.has(index) ? '★' : '☆'; button.addEventListener('click', () => { saved.has(index) ? saved.delete(index) : saved.add(index); localStorage.setItem(key, JSON.stringify([...saved])); render(); }); head.append(button); const arabic = document.createElement('p'); arabic.className='hadis-arabic'; arabic.lang='ar'; arabic.dir='rtl'; arabic.textContent=hadis.arabic; const translation=document.createElement('p'); translation.className='hadis-translation'; translation.textContent=hadis.malay; card.append(head,arabic,translation); list.append(card); }); };
  search.addEventListener('input',render); filter.addEventListener('click',()=>{ const active=filter.getAttribute('aria-pressed')==='true'; filter.setAttribute('aria-pressed',String(!active)); render(); }); render();
})();
